Repository BaSP-a2022/alfon-b-trackgenix-app, pull requests merged in 2022-11, with the labels that each got.

#28 BaSP-TG-47: tasks - put and post
  src/Components/Employees/index.js
  src/Components/Tasks/Form/index.js
  src/redux/employees/thunks.js
  src/redux/tasks/actions.js
  src/redux/tasks/constants.js
  src/redux/tasks/reducer.js
  src/redux/tasks/thunks.js
Labels: Ready to merge

#26 BaSP-TG-42: Redux - Super Admin
  src/Components/Admins/index.js
  src/Components/SuperAdmins/Form/index.js
  src/Components/SuperAdmins/index.js
  src/redux/admins/reducer.js
  src/redux/admins/thunks.js
  src/redux/superAdmins/actions.js
  src/redux/superAdmins/constants.js
  src/redux/superAdmins/reducer.js
  src/redux/superAdmins/thunks.js
Labels: Ready to merge

#29 BaSP-TG-49: projects - put and post
  src/Components/Projects/Form/index.js
  src/Components/Shared/Input/index.js
  src/Components/Shared/Select/index.js
  src/redux/projects/actions.js
  src/redux/projects/constants.js
  src/redux/projects/reducer.js
  src/redux/projects/thunks.js
Labels: Ready to merge

#35 BaSP-TG-54: Setup week 14
  jsconfig.json
  package-lock.json
  package.json
  src/Components/Admins/FormAdmins/index.js
  src/Components/Admins/index.js
  src/Components/Shared/index.js
Labels: Ready to merge

#39 BaSP-TG-57: Implement react hooks form
  src/Components/Admins/FormAdmins/index.js
  src/Components/Employees/Form/index.js
  src/Components/Projects/Form/form.module.css
  src/Components/Projects/Form/index.js
  src/Components/Shared/Form/index.js
  src/Components/Shared/Input/index.js
  src/Components/Shared/Select/index.js
  src/Components/SuperAdmins/Form/index.js
  src/Components/Tasks/Form/index.js
  src/Components/TimeSheets/Form/TimesheetsForm.jsx
  src/redux/tasks/thunks.js
Labels: Ready for QA, Ready to merge

#41 BaSP-TG-64: Replace relative routes with absolute routes
  src/Components/Employees/Form/index.js
  src/Components/Employees/index.js
  src/Components/Footer/index.js
  src/Components/Header/index.js
  src/Components/Home/index.js
  src/Components/Projects/Form/index.js
  src/Components/Projects/index.js
  src/Components/Routes/index.js
  src/Components/Shared/Buttons/FunctionalButton.jsx
  src/Components/Shared/Buttons/RedirectButton.jsx
  src/Components/Shared/Form/index.js
  src/Components/Shared/Input/index.js
  src/Components/Shared/Modal/index.js
  src/Components/Shared/Select/index.js
  src/Components/Shared/Spinner/index.js
  src/Components/Shared/Table/index.js
  src/Components/Shared/Table/tableRow.js
  src/Components/Shared/index.js
  src/Components/SuperAdmins/Form/index.js
  src/Components/SuperAdmins/index.js
  src/Components/Tasks/Form/index.js
  src/Components/Tasks/index.js
  src/Components/TimeSheets/Form/TimesheetsForm.jsx
  src/Components/TimeSheets/index.jsx
  src/index.js
Labels: Ready for QA
